name: ci

on: 
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      
      - name: Install oci-cli
        uses: danielwoodz/oci-cli-action@v1.0.2
        with:
          user: "${{ secrets.OCI_USER }}"
          fingerprint: "${{ secrets.OCI_FINGERPRINT }}"
          tenancy: "${{ secrets.OCI_TENANCY }}"
          region: "${{ secrets.OCI_REGION }}"
          api_key: |
            ${{ secrets.OCI_API_KEY }}
          verbose: true

      - run: cat ~/.oci/config

      - run: oci -v
